# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-05-24T17:35:16+00:00

from __future__ import annotations
from pydantic import AnyUrl, AwareDatetime, BaseModel, Field
from typing import Any
from enum import Enum, StrEnum


class StartupCaptureConfig(BaseModel):
    enabled: bool = Field(
        ..., description="When true, the daemon opens a diagnostics capture at boot."
    )
    duration_seconds: int = Field(
        ...,
        description="Duration of the boot-time capture. Zero falls back to the default (300 s).",
        ge=0,
        le=1800,
    )
    anonymise: bool = Field(
        ...,
        description="Whether to hash device-address-shaped values in the recorded archive.",
    )


class ExportedConfiguration(BaseModel):
    version: str = Field(
        ..., description='Serialisation format version. Always "1.0".', examples=["1.0"]
    )
    exported_at: AwareDatetime = Field(
        ..., description="UTC instant at which the snapshot was taken."
    )
    central_name: str | None = Field(
        None,
        description="CCU name that owns this channel (multi-CCU safe). Empty for single-CCU setups.\n",
    )
    device_address: str = Field(
        ..., description='Serial / address of the parent device, e.g. "0001ABCD".'
    )
    model: str = Field(..., description='Device model string, e.g. "HmIP-eTRV-2".')
    channel_address: str = Field(
        ...,
        description='Full channel address including channel index, e.g. "0001ABCD:1".',
    )
    channel_type: str = Field(
        ..., description='Functional type of the channel, e.g. "CLIMATE_TRANSCEIVER".'
    )
    paramset_key: str = Field(
        ...,
        description='Name of the exported paramset, typically "MASTER" or "VALUES".',
    )
    values: dict[str, Any] = Field(
        ..., description="Parameter name → value mapping captured at export time."
    )


class Priority(StrEnum):
    critical = "critical"
    high = "high"
    default = "default"
    low = "low"


class CustomDPInvokeRequest(BaseModel):
    params: dict[str, Any] | None = Field(
        None, description="Operation-specific parameters (category-dependent)."
    )
    priority: Priority | None = None


class CustomDPSummary(BaseModel):
    name: str
    category: str
    channel_no: int
    supported_operations: list[str]
    kind: str | None = Field(
        None,
        description="Stable widget hint derived from the concrete Custom-DP\ntype — e.g. `light`, `light_color`, `light_color_temp`,\n`light_fixed_color`, `light_rgbw`, `cover_blind`,\n`cover_garage`, `climate_hmip`, `climate_rf`,\n`climate_simple`, `lock`, `siren`, `switch`,\n`text_display`. Drives the SPA's CDP-aware widget\nselection (ADR 0016). Empty when the kind classifier\ndoes not recognise the Custom-DP type.\n",
    )
    channels: list[int] | None = Field(
        None,
        description="CCU channels this Custom-DP is materialised on. The\ncurrent implementation always contains exactly the\nprimary channel (matching `channel_no`); future\niterations may expand to include sibling channels\npulled in via the `RebasedChannelGroupConfig`\nmechanism.\n",
    )
    capabilities: dict[str, bool] | None = Field(
        None,
        description="Flat string→bool map of optional features the device\nsupports — e.g. `dimmable`, `color`, `color_temp`,\n`effects`, `tilt`, `boost`, `away`. Mirrors the\nper-category Capability struct from\n`internal/model/custom/mixins.go`.\n",
    )


class Type(Enum):
    https___openccu_loom_dev_errors_validation = (
        "https://openccu-loom.dev/errors/validation"
    )
    https___openccu_loom_dev_errors_not_found = (
        "https://openccu-loom.dev/errors/not_found"
    )
    https___openccu_loom_dev_errors_conflict = (
        "https://openccu-loom.dev/errors/conflict"
    )
    https___openccu_loom_dev_errors_unauthorized = (
        "https://openccu-loom.dev/errors/unauthorized"
    )
    https___openccu_loom_dev_errors_forbidden = (
        "https://openccu-loom.dev/errors/forbidden"
    )
    https___openccu_loom_dev_errors_unsupported = (
        "https://openccu-loom.dev/errors/unsupported"
    )
    https___openccu_loom_dev_errors_rate_limited = (
        "https://openccu-loom.dev/errors/rate_limited"
    )
    https___openccu_loom_dev_errors_internal = (
        "https://openccu-loom.dev/errors/internal"
    )
    https___openccu_loom_dev_errors_bad_request = (
        "https://openccu-loom.dev/errors/bad_request"
    )
    https___openccu_loom_dev_errors_service_unready = (
        "https://openccu-loom.dev/errors/service_unready"
    )
    https___openccu_loom_dev_errors_upstream_unavailable = (
        "https://openccu-loom.dev/errors/upstream_unavailable"
    )


class Code(StrEnum):
    validation = "validation"
    not_found = "not_found"
    conflict = "conflict"
    unauthorized = "unauthorized"
    forbidden = "forbidden"
    unsupported = "unsupported"
    rate_limited = "rate_limited"
    internal = "internal"
    bad_request = "bad_request"
    service_unready = "service_unready"
    upstream_unavailable = "upstream_unavailable"


class Error(BaseModel):
    field: str | None = None
    reason: str | None = None
    min: Any | None = None
    max: Any | None = None


class Problem(BaseModel):
    type: Type = Field(
        ...,
        description="Stable URI for one of the canonical problem kinds. All\nURIs share the base `https://openccu-loom.dev/errors/`\nand the trailing segment matches the `code` enum below.\nThe base URI is a stable identifier, not a fetchable\nresource — it is not guaranteed to resolve to a document.\n",
    )
    title: str
    status: int
    detail: str | None = None
    instance: str | None = None
    code: Code | None = Field(
        None,
        description="Short tag (also surfaced as the `X-Problem-Code` response header).",
    )
    errors: list[Error] | None = None


class Capability(StrEnum):
    rest_v1 = "rest.v1"
    ws_broadcasts_v1 = "ws.broadcasts.v1"
    errors_problem_details_v1 = "errors.problem_details.v1"
    mqtt_discovery_v1 = "mqtt.discovery.v1"
    matter_bridge_v1 = "matter.bridge.v1"
    auth_oidc_v1 = "auth.oidc.v1"


class Info(BaseModel):
    version: str = Field(..., description="Daemon build version (semver).")
    commit: str
    build_date: str
    uptime: str
    started_at: AwareDatetime
    api_version: str = Field(
        ...,
        description="North-bound contract version (semver). Bumps independently\nof `version`. Minor bumps add backwards-compatible\ncapabilities; major bumps remove or rename existing\npayload fields, scopes, or capabilities.\n",
    )
    capabilities: list[Capability] = Field(
        ...,
        description="Runtime feature set. Always-on entries:\n`rest.v1`, `ws.broadcasts.v1`, `errors.problem_details.v1`.\nConditional entries surface only when configured:\n`mqtt.discovery.v1`, `matter.bridge.v1`, `auth.oidc.v1`.\n",
    )


class SystemCCUEntry(BaseModel):
    name: str
    host: str
    available: bool
    model: str | None = None
    version: str | None = None
    hostname: str | None = None
    serial: str | None = None
    url: AnyUrl | None = None
    is_ha_app: bool
    configured_interfaces: list[str]


class Status(StrEnum):
    healthy = "healthy"
    degraded = "degraded"
    unhealthy = "unhealthy"
    unknown = "unknown"


class Component(BaseModel):
    name: str
    status: str
    note: str | None = None
    recorded_at: AwareDatetime


class Health(BaseModel):
    status: Status
    components: list[Component]


class Central(BaseModel):
    name: str | None = None
    host: str | None = None
    interfaces: list[str] | None = None


class CallbackPorts(BaseModel):
    xmlrpc: int | None = None
    binrpc: int | None = None


class ConfigSnapshot(BaseModel):
    locale: str | None = None
    centrals: list[Central] | None = None
    callback_ports: CallbackPorts | None = None
    features: dict[str, bool] | None = None
    extras: dict[str, str] | None = None
    policies: dict[str, bool] | None = Field(
        None,
        description="Static daemon-side behaviour switches. Keys are stable;\nvalues reflect the current effective policy. See the\n`/config` path-level description for the canonical key\ncatalogue.\n",
    )


class DeviceSummary(BaseModel):
    address: str
    interface: str
    interface_id: str | None = None
    model: str
    sub_model: str | None = None
    name: str
    manufacturer: str | None = None
    product_group: str | None = None
    available: bool
    channels_count: int
    updatable: bool | None = None
    rooms: list[str] | None = None


class DeviceList(BaseModel):
    items: list[DeviceSummary]
    page: int
    per_page: int
    total: int


class Firmware(BaseModel):
    Current: str | None = None
    Available: str | None = None
    Updatable: bool | None = None
    UpdateState: str | None = None


class Availability(BaseModel):
    IsReachable: bool | None = None
    LastUpdated: AwareDatetime | None = None
    BatteryLevel: int | None = None
    LowBattery: bool | None = None
    SignalStrength: int | None = None


class ChannelSummary(BaseModel):
    address: str
    number: int
    paramset_key: str
    data_points_count: int
    custom_dp_name: str | None = Field(
        None,
        description="Stable name of the Custom-DP this channel is attached to.\nEmpty when the channel is not owned by any CDP. Lets the\nSPA's CDP-first Übersicht view (ADR 0016) filter channels\nthat are already represented by a CDP tile.\n",
    )


class ValuesCacheStats(BaseModel):
    rows: int = Field(..., description="Current row count in the cache.")
    value_json_bytes: int = Field(
        ..., description="Sum of value_json byte sizes across all rows."
    )
    restored_rows: int = Field(
        ..., description="Cumulative rows successfully restored since process start."
    )
    cast_failures: int = Field(
        ...,
        description="Cumulative entries whose cached value could not be coerced into the data point's static type.",
    )
    gc_rows_deleted: int = Field(
        ...,
        description="Cumulative rows removed by the dead-row GC since process start.",
    )
    flush_batches: int = Field(
        ...,
        description="Cumulative SaveBatch transactions committed since process start.",
    )
    flushed_entries: int = Field(
        ..., description="Cumulative entries written across all SaveBatch transactions."
    )


class Source(StrEnum):
    unobserved = "unobserved"
    cache = "cache"
    live = "live"
    stale = "stale"


class Operations(BaseModel):
    read: bool
    write: bool
    event: bool


class UiHint(BaseModel):
    icon: str = Field(
        ..., description='Material Design Icons token, e.g. "mdi:thermometer".'
    )
    semantic: str = Field(
        ...,
        description='Stable token used by the composer to group readouts\nof the same physical quantity into one bucket\n(e.g. "temperature", "particulate", "motion").\n',
    )
    state_color_rule: str | None = Field(
        None,
        description='Named threshold rule the SPA looks up in its rule\nregistry to colour the readout (e.g. "temp_heat",\n"alarm_active", "signal_weak"). Empty when no rule.\n',
    )


class DataPointSummary(BaseModel):
    parameter: str
    parameter_label: str | None = None
    value: Any | None = None
    observed: bool
    modified_at: AwareDatetime | None = Field(
        None,
        description="When the value last changed on the CCU. RFC3339Nano,\nUTC. Equivalent to `last_changed_at` (kept for\ncache-friendly naming alongside `last_seen_at`).\n",
    )
    source: Source | None = Field(
        None,
        description="Wire-side lifecycle token. See ADR 0018.\n- unobserved: never seen any value\n- cache: restored from persistent cache at boot, awaiting live event\n- live: last value confirmed by CCU push / fetch_all, connection healthy\n- stale: connection lost; value is the last known good\n",
    )
    last_seen_at: AwareDatetime | None = Field(
        None,
        description="When the data point was last observed via any push or\nfetch_all event (cyclic info telegrams included). Advances\neven when the value did not change.\n",
    )
    last_changed_at: AwareDatetime | None = Field(
        None,
        description="When the value actually changed last. Alias of modified_at\nkept under the cache-friendly name.\n",
    )
    value_age_seconds: int | None = Field(
        None,
        description="Pre-computed seconds between last_seen_at and the response\ntime, so the browser does not need to parse the timestamp\non every render.\n",
    )
    operations: Operations
    control: str | None = Field(
        None,
        description="CCU paramset descriptor's CONTROL attribute of the form\nWIDGET_FAMILY.SLOT (e.g. \"HEATING_CONTROL_HMIP.SETPOINT\").\nDrives the SPA's CONTROL-aware widget resolver. See\ndocs/ui/control-widget-concept.md. Empty when the\ndescriptor carries no CONTROL.\n",
    )
    type: str | None = Field(
        None,
        description="CCU descriptor TYPE (BOOL, INTEGER, FLOAT, ENUM, STRING, ACTION).\nSurfaced so the SPA can pick the right widget primitive\nwithout re-reading the paramset descriptor.\n",
    )
    value_list: list[str] | None = Field(
        None,
        description='Ordered enum labels for ENUM-typed parameters\n(e.g. ["BLACK","BLUE","GREEN","TURQUOISE","RED","PURPLE",\n"YELLOW","WHITE"] on HmIP-BSL COLOR). Empty for non-ENUM.\n',
    )
    unit: str | None = Field(
        None,
        description='Descriptor UNIT string ("°C", "% rF", "lx", "Wh", ...)\nas the CCU declares it. Empty when none.\n',
    )
    min: Any | None = None
    max: Any | None = None
    default: Any | None = None
    ui_hint: UiHint | None = Field(
        None,
        description="Daemon-computed UI classification envelope. The SPA's\nAutoTile composer reads the fields verbatim — no JS-side\nclassification runs. See docs/ui/auto-tile-concept.md.\nResolution order in the backend: parameter substring →\nENUM-shape rules → unit table → type fallback. Never\nempty.\n",
    )


class UIEventRequest(BaseModel):
    event: str = Field(
        ..., description="Event name (e.g. `device_detail.view_selector`)."
    )
    properties: dict[str, Any] | None = Field(
        None, description="Optional event-specific key/value attributes."
    )


class SetValueRequest(BaseModel):
    value: Any
    priority: Priority | None = None


class ProgramSummary(BaseModel):
    id: str
    name: str
    description: str | None = None
    active: bool | None = None


class SysvarSummary(BaseModel):
    name: str
    description: str | None = None
    unit: str | None = None
    value_type: str
    value: Any | None = None
    observed: bool
    value_list: list[str] | None = None


class SysvarSetRequest(BaseModel):
    value: Any


class Change(BaseModel):
    parameter: str
    before: Any | None = None
    after: Any | None = None


class AuditEntry(BaseModel):
    timestamp: AwareDatetime = Field(
        ..., description="UTC time at which the change was recorded."
    )
    user: str | None = Field(
        None,
        description="Authenticated user who triggered the change (empty if unauthenticated).",
    )
    action: str = Field(
        ...,
        description="Stable action tag, e.g. paramset_write, link_add, data_point_write. New values may be added in future releases.\n",
    )
    device_address: str | None = Field(
        None, description="Primary device or channel address, if applicable."
    )
    channel_no: int | None = Field(
        None, description="Channel number within the device, if applicable."
    )
    paramset: str | None = Field(
        None, description="Paramset type (MASTER, VALUES, LINK), if applicable."
    )
    peer: str | None = Field(None, description="Peer address for link operations.")
    parameter: str | None = Field(
        None, description="Parameter name for single-parameter writes."
    )
    note: str | None = Field(
        None,
        description="Free-form context (e.g. profile ID for active_profile changes).",
    )
    changes: list[Change] | None = Field(
        None, description="Per-parameter before/after pairs for paramset writes."
    )


class AlarmMessage(BaseModel):
    id: str
    name: str
    description: str | None = None
    device_name: str | None = None
    timestamp: AwareDatetime
    counter: int
    last_trigger: str | None = None
    rooms: list[str] | None = None


class ServiceMessage(BaseModel):
    id: str
    name: str
    address: str | None = None
    device_name: str | None = None
    type: str | None = None
    timestamp: AwareDatetime
    counter: int
    quittable: bool | None = None


class InstallModeState(BaseModel):
    active: bool
    seconds: int | None = Field(None, ge=0)


class InterfaceState(BaseModel):
    id: str
    name: str
    connected: bool
    interface: str
    central_id: str | None = None
    host: str | None = None
    note: str | None = None


class Room(BaseModel):
    name: str
    device_count: int


class Function(BaseModel):
    name: str
    device_count: int


class Snapshot(BaseModel):
    generated_at: AwareDatetime
    devices: list[DeviceSummary]
    programs: list[ProgramSummary] | None = None
    sysvars: list[SysvarSummary] | None = None
    rooms: list[Room] | None = None
    functions: list[Function] | None = None
    interfaces: list[InterfaceState] | None = None


class Role(StrEnum):
    admin = "admin"
    operator = "operator"
    viewer = "viewer"


class Scheme(StrEnum):
    basic = "basic"
    bearer = "bearer"
    session = "session"
    oidc = "oidc"


class Identity(BaseModel):
    subject: str
    role: Role
    scheme: Scheme | None = None


class UserListEntry(BaseModel):
    username: str
    role: Role


class TokenListEntry(BaseModel):
    id: str = Field(
        ...,
        description="Stable management identifier (16 hex chars from sha256 of the token).",
    )
    fingerprint: str = Field(
        ..., description="Last six characters of the token; full value is never exposed"
    )
    subject: str
    role: Role


class Query(BaseModel):
    address: str
    channel: int = Field(..., ge=0)
    parameter: str


class ValuesBatchRequest(BaseModel):
    queries: list[Query] = Field(..., max_length=1000)


class Result(BaseModel):
    address: str
    channel: int = Field(..., ge=0)
    parameter: str
    summary: DataPointSummary | None = None
    error: str | None = Field(
        None,
        description="Per-query failure. Set when `summary` is absent.\nStable values: `device not found`,\n`channel not found`, `parameter not found`,\n`parameter hidden`.\n",
    )


class ValuesBatchResponse(BaseModel):
    results: list[Result]


class CreateTokenResponse(BaseModel):
    id: str = Field(..., description="Stable management identifier.")
    token: str = Field(
        ..., description="Raw bearer token. URL-safe base64 (~43 chars)."
    )
    fingerprint: str
    subject: str
    role: Role


class MatterFabric(BaseModel):
    fabric_index: int = Field(
        ...,
        description="Stack-assigned fabric index per Matter Core Spec §11.18.5",
        ge=1,
        le=254,
    )
    fabric_id: int
    node_id: int
    vendor_id: int = Field(..., ge=0, le=65535)
    label: str | None = None
    compressed_id: str = Field(
        ..., description="8-byte compressed fabric identifier, hex-encoded"
    )
    root_public_key: str = Field(
        ...,
        description="Issuing root CA public key (uncompressed P-256, 65 bytes), hex-encoded",
    )


class MatterFabricList(BaseModel):
    fabrics: list[MatterFabric]


class MatterSetupPayload(BaseModel):
    discriminator: int = Field(..., ge=0, le=4095)
    passcode: int = Field(..., ge=1, le=99999998)
    vendor_id: int = Field(..., ge=0, le=65535)
    product_id: int = Field(..., ge=0, le=65535)
    qr_code: str = Field(
        ..., description="Onboarding payload prefixed with `MT:` per Matter §5.7.4"
    )
    manual_code: str = Field(
        ...,
        description="11-digit decimal code with Verhoeff check digit per Matter §5.1.4",
    )


class MatterCommissioningWindowRequest(BaseModel):
    duration_seconds: int | None = Field(
        None,
        description="Commissioning window duration in seconds. Default 900 (15 minutes).",
        ge=180,
        le=900,
    )


class MatterCommissioningWindowResponse(BaseModel):
    discriminator: int = Field(..., ge=0, le=4095)
    passcode: int = Field(..., ge=1, le=99999998)
    duration_seconds: int = Field(..., ge=180, le=900)
    qr_code: str
    manual_code: str


class MatterStatus(BaseModel):
    enabled: bool = Field(..., description="Bridge feature flag")
    listening: bool = Field(..., description="UDP listener bound")
    listen_addr: str | None = Field(None, description="Effective UDP listen address")
    endpoint_count: int = Field(
        ..., description="Bridged-endpoint count (excluding root)"
    )
    fabric_count: int = Field(..., description="Commissioned fabrics")
    enabled_count: int = Field(..., description="Allowlist entries with enabled=true")
    advertising: bool = Field(..., description="mDNS records emitted")
    commissioning_window_open: bool
    commissioning_window_duration_seconds: int | None = Field(None, ge=0, le=900)


class DpKind(StrEnum):
    custom = "custom"
    generic = "generic"
    calculated = "calculated"
    combined = "combined"
    measurement = "measurement"


class Mappable(StrEnum):
    mappable = "mappable"
    partially_mappable = "partially_mappable"
    unmappable = "unmappable"


class MatterExposure(BaseModel):
    central_name: str
    device_address: str
    channel_no: int
    dp_kind: DpKind
    dp_key: str
    display_name: str | None = None
    enabled: bool
    friendly_name: str | None = None
    mappable: Mappable
    device_type: int | None = Field(None, ge=0, le=65535)
    clusters: list[int] | None = None
    reason: str | None = None


class MatterExposureList(BaseModel):
    items: list[MatterExposure]


class MatterExposureUpdate(BaseModel):
    central_name: str
    device_address: str
    channel_no: int
    dp_kind: DpKind
    dp_key: str
    enabled: bool
    friendly_name: str | None = None


class MatterExposureBulkUpdate(BaseModel):
    items: list[MatterExposureUpdate]


class UnIgnoreEntry(BaseModel):
    pattern: str
    updated_at: AwareDatetime | None = None
    updated_by: str | None = None


class Central1(BaseModel):
    central_name: str
    patterns: list[UnIgnoreEntry]


class UnIgnoreListResponse(BaseModel):
    centrals: list[Central1]


class UnIgnoreUpdateRequest(BaseModel):
    central_name: str
    patterns: list[str]


class UnIgnoreUpdateResponse(BaseModel):
    applied_count: int
    parse_errors: list[str] | None = None
    affected_devices: int | None = None
    patterns: list[UnIgnoreEntry] | None = None


class UnIgnoreCandidateList(BaseModel):
    candidates: list[str]
    include_master: bool | None = None


class Kind(StrEnum):
    initial = "initial"
    change = "change"
    refresh = "refresh"


class WsEnvelope(BaseModel):
    seq: int = Field(
        ...,
        description='Monotonic, daemon-assigned sequence number. Strictly\nincreasing across the daemon\'s lifetime (resets to 0\non restart). Clients store the last received `seq` and\nreconnect with `{op:"subscribe", topics:[...], since:N}`\nto resume the stream.\n',
        ge=1,
    )
    kind: Kind = Field(
        ...,
        description="Event-family discriminator. `change` is the default\nand dominant case; `initial` is set on the first\nobservation of a data point (e.g. during cold-start\nreplay); `refresh` is reserved for periodic re-emits.\n",
    )
    topic: str | None = Field(
        None,
        description="Routing key the client subscribed to. Absent on command replies.",
    )
    type: str = Field(
        ..., description="Event-type discriminator (e.g. `datapoint.value_changed`)."
    )
    ts: AwareDatetime = Field(
        ..., description="RFC3339Nano timestamp (UTC) of when the event was emitted."
    )
    payload: Any = Field(..., description="One of the payload schemas listed below.")


class DataPointValueChangedPayload(BaseModel):
    central: str
    interface: str | None = None
    device_address: str
    channel: int = Field(..., ge=0)
    parameter: str
    paramset_key: str = Field(..., description="VALUES, MASTER, or LINK")
    value: Any = Field(
        ...,
        description="New value in its native CCU type (bool/int/float/string/list/null).",
    )
    previous: Any | None = Field(
        None,
        description='Prior value. Omitted when no prior value was tracked (initial\npush). Future revisions may surface a `kind: "initial"|"change"|"refresh"`\ndiscriminator on the envelope; see docs/external-clients/asks.md (B2).\n',
    )
    modified_at: AwareDatetime = Field(
        ..., description="RFC3339Nano timestamp the CCU observed the change at."
    )


class CustomDataPointStateChangedPayload(BaseModel):
    central: str
    device_address: str
    channel: int = Field(..., ge=0)
    name: str
    kind: str | None = Field(
        None,
        description="Widget hint matching CustomDPSummary.kind (e.g. `light`, `cover_blind`).",
    )
    state: dict[str, Any] = Field(
        ..., description="Composed state snapshot — keys depend on the CDP category."
    )


class CentralStateChangedPayload(BaseModel):
    central: str
    old_state: str
    new_state: str


class SystemStatusChangedPayload(BaseModel):
    central: str
    component: str
    healthy: bool
    reason: str | None = None
    interface_id: str | None = None
    error_code: int | None = None
    central_state: str | None = Field(
        None, description="hmenum.CentralState string form"
    )
    connection_state: str | None = None
    client_state: str | None = Field(None, description="hmenum.ClientState string form")
    callback_state: str | None = None
    degraded_interfaces: list[str] | None = None
    issues: list[str] | None = None
    event_at: AwareDatetime


class SysvarChangedPayload(BaseModel):
    central: str
    name: str
    value_type: str | None = Field(
        None, description="hmenum.HubValueType (BOOL, FLOAT, INTEGER, STRING, …)."
    )
    value: Any = Field(..., description="New sysvar value in its native CCU type.")
    previous: Any | None = Field(
        None, description="Prior sysvar value; omitted when no prior value was tracked."
    )


class ProgramExecutedPayload(BaseModel):
    central: str
    program_id: str
    trigger: str | None = Field(
        None, description="hmenum.ProgramTrigger (MANUAL, SCHEDULE, EVENT, …)."
    )
    success: bool


class MatterCommissioningProgressPayload(BaseModel):
    stage: str = Field(
        ...,
        description="Stage label (e.g. `pase_session_open`, `add_noc`, `case_session_first`).",
    )
    message: str | None = Field(
        None, description="Human-readable detail; may be empty."
    )


class MatterFabricRemovedPayload(BaseModel):
    fabric_index: int = Field(
        ...,
        description="Stack-assigned fabric index of the removed fabric.",
        ge=1,
        le=254,
    )


class MatterEndpointAssembledPayload(BaseModel):
    endpoint_count: int = Field(
        ...,
        description="Number of endpoints in the assembled topology, including the root + Aggregator.",
        ge=0,
    )


class DeviceDetail(DeviceSummary):
    firmware: Firmware | None = None
    availability: Availability | None = None
    channels: list[ChannelSummary] | None = None
