# SPDX-License-Identifier: MIT
# Copyright (C) 2026 OpenCCU-Loom authors.

"""Re-export of WebSocket envelope + push-payload Pydantic models.

DO NOT EDIT BY HAND — run `make generate-ws` after the daemon repo's
`make export-schemas` + this repo's `make generate-rest` have run.

The underlying classes live in :mod:`openccu_loom_types.rest`
(generated by datamodel-codegen from the daemon's openapi.yaml).
This module re-exports the subset that appears as `payload` in any
WebSocket broadcast catalogued in `assets/wsapi.json`, plus the
envelope itself, so external clients can write:

    from openccu_loom_types.ws import WsEnvelope, DataPointValueChangedPayload

without knowing the schemas physically sit in the REST module.
"""

from __future__ import annotations

from openccu_loom_types.rest import (
    WsEnvelope,
    CentralStateChangedPayload,
    CustomDataPointStateChangedPayload,
    DataPointValueChangedPayload,
    ProgramExecutedPayload,
    SysvarChangedPayload,
    SystemStatusChangedPayload,
    MatterExposureUpdate,
    MatterCommissioningWindowResponse,
    MatterCommissioningProgressPayload,
    MatterFabric,
    MatterFabricRemovedPayload,
    MatterEndpointAssembledPayload,
)

__all__ = [
    "WsEnvelope",
    "CentralStateChangedPayload",
    "CustomDataPointStateChangedPayload",
    "DataPointValueChangedPayload",
    "ProgramExecutedPayload",
    "SysvarChangedPayload",
    "SystemStatusChangedPayload",
    "MatterExposureUpdate",
    "MatterCommissioningWindowResponse",
    "MatterCommissioningProgressPayload",
    "MatterFabric",
    "MatterFabricRemovedPayload",
    "MatterEndpointAssembledPayload",
]
