#!/usr/bin/env python3
"""Generate openccu_loom_types/ws.py as a re-export from rest.py.

The WS envelope + push-payload schemas live in the same
`components.schemas` block of the daemon's openapi.yaml as the REST
DTOs, so datamodel-codegen already materialises them inside
`rest.py`. Rather than running a second generator against the same
source document (and dealing with name-collision / drift), this
script produces `ws.py` as a thin re-export module — the public
import path `openccu_loom_types.ws` resolves to exactly the same
Pydantic class objects as `openccu_loom_types.rest`.

The class list is sourced from the daemon's wsapi.json broadcast
catalogue (the only authoritative listing of which OpenAPI schemas
are WS-relevant). `WsEnvelope` is always included.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


HEADER = '''# SPDX-License-Identifier: MIT
# Copyright (C) 2026 OpenCCU-Loom authors.

"""Re-export of WebSocket envelope + push-payload Pydantic models.

DO NOT EDIT BY HAND — run `make generate-ws` after the daemon repo's
`make export-schemas` + this repo's `make generate-rest` have run.

The underlying classes live in :mod:`openccu_loom_types.rest`
(generated by datamodel-codegen from the daemon's openapi.yaml).
This module re-exports the subset that appears as `payload` in any
WebSocket broadcast catalogued in `assets/wsapi.json`, plus the
envelope itself, so external clients can write:

    from openccu_loom_types.ws import WsEnvelope, DataPointValueChangedPayload

without knowing the schemas physically sit in the REST module.
"""

from __future__ import annotations

'''


def class_names_from_wsapi(wsapi_path: Path) -> list[str]:
    """Pull the set of WS-related schema names from wsapi.json.

    Always returns `WsEnvelope` first, then the deduplicated list of
    `payload` values from every broadcast entry in stable order.
    """
    doc = json.loads(wsapi_path.read_text())
    names: list[str] = ["WsEnvelope"]
    seen = {"WsEnvelope"}
    for cmd in doc.get("commands", []):
        if cmd.get("kind") != "broadcast":
            continue
        payload = cmd.get("payload")
        if not payload or payload in seen:
            continue
        seen.add(payload)
        names.append(payload)
    return names


def existing_classes(rest_path: Path) -> set[str]:
    """Return the set of `class Name(...)` symbols defined in rest.py
    so we can fail fast if wsapi.json points at a schema the REST
    generator did not actually produce.
    """
    text = rest_path.read_text()
    return set(re.findall(r"^class (\w+)\(", text, re.MULTILINE))


def emit(out_path: Path, names: list[str]) -> None:
    parts = [HEADER, "from openccu_loom_types.rest import (\n"]
    for n in names:
        parts.append(f"    {n},\n")
    parts.append(")\n\n__all__ = [\n")
    for n in names:
        parts.append(f"    {json.dumps(n)},\n")
    parts.append("]\n")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("".join(parts))


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--wsapi-json", required=True, type=Path,
                   help="Path to assets/wsapi.json in the daemon repo.")
    p.add_argument("--rest-py", required=True, type=Path,
                   help="Path to openccu_loom_types/rest.py.")
    p.add_argument("--out-py", required=True, type=Path)
    args = p.parse_args()

    if not args.wsapi_json.is_file():
        print(f"wsapi.json not found: {args.wsapi_json}", file=sys.stderr)
        return 1
    if not args.rest_py.is_file():
        print(f"rest.py not found: {args.rest_py}", file=sys.stderr)
        return 1

    names = class_names_from_wsapi(args.wsapi_json)
    available = existing_classes(args.rest_py)
    missing = [n for n in names if n not in available]
    if missing:
        print("rest.py is missing classes referenced by wsapi.json broadcasts:",
              file=sys.stderr)
        for m in missing:
            print(f"  - {m}", file=sys.stderr)
        print("Run `make generate-rest` first; if that does not produce them,",
              file=sys.stderr)
        print("the OpenAPI schema is out of sync with the broadcast catalogue.",
              file=sys.stderr)
        return 1

    emit(args.out_py, names)
    print(f"wrote {len(names)} re-exports to {args.out_py}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
